data:
  # image: tianon/true:latest (docker/fig#919)
  image: busybox:latest
  volumes:
    - /data
  command: /bin/echo

redis:
  restart: always
  image: redis:2.8
  volumes_from:
    - data
  command: redis-server --appendonly yes

www:
  restart: always
  build: .
  links:
    - redis
  ports:
    - "8080"
  environment:
    NODE_ENV:
    SLACK_TOKEN:
    SPRINTLY_PRODUCT:

builder:
  build: .
  links:
    - redis
  volumes:
    - Gruntfile.coffee:/usr/src/app/Gruntfile.coffee:ro
    - lib/:/usr/src/app/lib
    - src/:/usr/src/app/src:ro
    - test/:/usr/src/app/test:ro
  command: true
  environment:
    NODE_ENV: development
    SLACK_TOKEN: abc123
    SPRINTLY_PRODUCT:
    SPRINTLY_USER_ID:
    SPRINTLY_USER:
    SPRINTLY_KEY:

