builder:
  build: .
  volumes:
    - Gruntfile.coffee:/usr/src/app/Gruntfile.coffee:ro
    - lib/:/usr/src/app/lib
    - src/:/usr/src/app/src:ro
    - test/:/usr/src/app/test:ro
  command: true
  environment:
    NODE_ENV: development
    SLACK_TOKEN: abc123
    SPRINTLY_PROJECT:
    SPRINTLY_USER:
    SPRINTLY_KEY:

www:
  restart: always
  build: .
  ports:
    - "8080"
  environment:
    NODE_ENV:
    SLACK_TOKEN:
    SPRINTLY_PROJECT:
    SPRINTLY_USER:
    SPRINTLY_KEY:

